config/routes.rb
Rails.application.routes.draw do
  devise_for :accesses  
  resources :panel
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :groups do
  	resources :users
  end
  root 'welcome#login'
end

app/models/access.rb
class Access < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :group
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :access
  has_many :user
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

	before_action :authenticate_access!
	def index
		@groups = current_access.group.all
	end	

	def new
		@group = Group.new
	end

	def create
		@group = current_access.group.new(name: params[:group][:name])
		if @group.save
			redirect_to groups_path
		end
	end

	def show
		@group = current_access.group.find(params[:id])
		@users = current_access.group.find(@group).user.all
	end
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController

	before_action :authenticate_access!

	def index
		@access = Access.all
	end	
	def show
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_access!

	def index		
	end	

	def new
		@group = current_access.group.find(params[:group_id])
		@user = User.new
	end

	def create
		@c_group = current_access.group.find(params[:group_id])
		@user = current_access.group.find(params[:group_id]).user.new(name: params[:user][:name])
		if @user.save
			redirect_to group_path(@c_group)
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def login
		
		if access_signed_in?
			redirect_to "/panel"
		else			
			redirect_to new_access_session_path		
		end		
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_options.html.erb
<div id="main-container">
	<div class="panel-menu">
		<div class="item">
			<div class="icon-item"></div>
			<div class="text-item be-white">
				<%= link_to "ADD GROUP", new_group_path, class: "middle-text no-list strong-gray"%>
			</div>
		</div>

		<div class="item">
			<div class="icon-item"></div>
			<div class="text-item be-white">
				<%= link_to "GROUPS", "/groups", class: "middle-text no-list strong-gray"%>
			</div>
		</div>
	</div>	
</div>

app/views/groups/index.html.erb
<%= render "options"%>

<div class="groups">
	<div class="info-container">
		<div class="header-table-one be-white">
			<div>
				<p>Name</p>
			</div>
			<div>
				<p>Action</p>
			</div>
		</div>
		<div class="list">
			<% @groups.each do |group|%>
				<div class="table-row be-white gray-border-bottom">
					<div class="item-1">
						<p><%= group.name %></p>						
					</div>
					<div class="item-2">
						<a href=<%= "groups/" + (group.id).to_s %>>
							<div class="table-icon delete"></div>	
						</a>
					</div>
					<div class="item-3">
						<a href=<%= "groups/" + (group.id).to_s %>>
							<div class="table-icon check"></div>
						</a>
					</div>			
				</div>
			<%end%>		
		</div>
	</div>
</div>

app/views/groups/new.html.erb
<%= render "options"%>

<div class="groups">
	<div class="be-white container-left-form box-radius">
		<div class="form-container">
		  <div class="topic-form text-center">
			<h2>Create a group</h2>
		  </div>
		  <%= form_for (@group)  do |f| %>
			<div class="field">
				<%= f.text_field :name, placeholder: "Group Name", class: "form-control gray-border-bottom"%>
			</div>
			<div class="actions top-space">
				<%= f.submit "Save", class: "btn-two be-aqua white large-padding"%>
			</div>
		  <%end%>
		  <!---%= render "devise/shared/links" %-->
		</div> 
	</div>
</div>

app/views/groups/show.html.erb

<div id="main-container">
	<div class="panel-menu">
		<div class="item">
			<div class="icon-item"></div>
			<div class="text-item be-white">
				<%= link_to "ADD USER",  new_group_user_path(@group), class: "middle-text no-list strong-gray"%>
			</div>
		</div>

		<div class="item">
			<div class="icon-item"></div>
			<div class="text-item be-white">
				<%= link_to "GROUPS", "/groups", class: "middle-text no-list strong-gray"%>
			</div>
		</div>
	</div>	
</div>
<!--%= render "options"%-->



<div class="groups">
	<div class="info-container">
		<div class="header-table-two">
			<div class="be-white">
				<p>Name</p>
			</div>
			<div class="be-white">
				<p>Delete</p>
			</div>
			<div class="be-white">
				<p>Take</p>
			</div>
		</div>
		<div class="list">
			<% @users.each do |user|%>
				<div class="table-row be-white gray-border-bottom">
					<div class="item-1">
						<p><%= user.name %></p>						
					</div>
					<div class="item-2">
						<a href=<%= "" %>>
							<div class="table-icon delete"></div>	
						</a>
					</div>
					<div class="item-3">
						<a href=<%= "" %>>
							<div class="table-icon take"></div>
						</a>
					</div>			
				</div>
			<%end%>		
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Attendance</title>

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if access_signed_in?%>
      <!--%= render "panel"%-->
      <div id="header-aside-left" class="be-strong-gray">
        <div class="logo-container be-aqua">
          <div>
            <div class="right" id="logo"></div>
          </div>
          <div>
            <h3 class="white">Attendance</h3>
          </div>
        </div>
        <div class="menu">
          <div class="block">
            <p class="strong-gray title-menu">--MAIN MENU--</p>
          </div>
          <div class="block selected-item">
            <div class="icon">
              <div></div>
            </div>
            <div class="text-menu">
              <%= link_to "DASHBOARD", root_path,class: "strong-gray no-list"%>
            </div>
          </div>
          <div class="block">
            <div class="icon"><div></div></div>
            <div class="text-menu">
              <%= link_to "GROUPS" , groups_path, class: "strong-gray no-list"%>
            </div>
          </div>
        </div>
      </div>

      <div id="header-aside-right" class="be-white">
        <div class="header-content">
          <div class="info-user">
            <p class="strong-gray"><%= current_access.email%></p>
          </div>
          <div>
            <a rel="nofollow" data-method="delete" href="/accesses/sign_out"><div class="l_out"></div></a>      
          </div>
        </div>
      </div>
    <%end%>
  	<!--p class="notice"><%= notice%></p>
  	<p class="alert"><%= alert%></p-->
    <%= yield %>
  </body>
</html>

app/views/panel/_panel.html.erb
<div id="header-aside-left" class="be-strong-gray">
	<div class="logo-container be-aqua">
		<div>
			<div class="right" id="logo"></div>
		</div>
		<div>
			<h3 class="white">Attendance</h3>
		</div>
	</div>
	<div class="menu">
		<div class="block">
			<p class="strong-gray title-menu">--MAIN MENU--</p>
		</div>
		<div class="block selected-item">
			<div class="icon">
				<div></div>
			</div>
			<div class="text-menu">
				<%= link_to "DASHBOARD", "",class: "strong-gray no-list"%>
			</div>
		</div>
		<div class="block">
			<div class="icon"><div></div></div>
			<div class="text-menu">
				<%= link_to "GROUPS" , "", class: "strong-gray no-list"%>
			</div>
		</div>
	</div>
</div>

<div id="header-aside-right" class="be-white">
	<div class="header-content">
		<div class="info-user">
			<p class="strong-gray">attendance@tryhard.com</p>
		</div>
		<div>
			<a rel="nofollow" data-method="delete" href="/accesses/sign_out"><div class="l_out"></div></a>			
		</div>
	</div>
</div>

<div id="main-container">
	<div class="panel-menu">
		<div class="item">
			<div class="icon-item"></div>
			<div class="text-item be-white">
				<%= link_to "ADD GROUP", new_group_path, class: "middle-text no-list strong-gray"%>
			</div>
		</div>

		<div class="item">
			<div class="icon-item"></div>
			<div class="text-item be-white">
				<%= link_to "GROUPS", "/groups", class: "middle-text no-list strong-gray"%>
			</div>
		</div>
	</div>	
</div>

app/views/panel/index.html.erb
<%= link_to "Salir", destroy_access_session_path, method: :delete%>

app/views/users/index.html.erb
<div class="groups">
	<h2>USERS</h2>
</div>

app/views/users/new.html.erb
<div id="main-container">
	<div class="panel-menu">
		<div class="item">
			<div class="icon-item"></div>
			<div class="text-item be-white">
				<%= link_to "ADD USER",  new_group_user_path(@group), class: "middle-text no-list strong-gray"%>
			</div>
		</div>

		<div class="item">
			<div class="icon-item"></div>
			<div class="text-item be-white">
				<%= link_to "GROUPS", "/groups", class: "middle-text no-list strong-gray"%>
			</div>
		</div>
	</div>	
</div>



<div class="groups">
	<div class="be-white container-left-form box-radius">
		<div class="form-container">
		  <div class="topic-form text-center">
			<h2>Create a user</h2>
		  </div>
		  <%= form_for ([@group,@user])  do |f| %>
			<div class="field">
				<%= f.text_field :name, placeholder: "Name", class: "form-control gray-border-bottom"%>
			</div>
			<div class="actions top-space">
				<%= f.submit "Save", class: "btn-two be-aqua white large-padding"%>
			</div>
		  <%end%>
		  <!---%= render "devise/shared/links" %-->
		</div> 
	</div>
</div>



app/views/welcome/login.html.erb
<%= link_to "Salir", destroy_access_session_path, method: :delete%>